version: "3"
services:
  db:
    container_name: dbcont
    image: abbasshaik739/project1:databaseimage
    ports:
      - "3306"
    

  auth_service:
    container_name: authcont
    image: abbasshaik739/project1:authimage
    ports:
      - "5001"
    

  book_service:
    container_name: bookcont
    image: abbasshaik739/project1:bookimage
    ports:
      - "5002"
    
    

  borrow_service:
    container_name: borrowcont
    image: abbasshaik739/project1:borrowimage
    ports:
      - "5003"
    

  frontend:
    container_name: appcont
    image: abbasshaik739/project1:appimage
    ports:
      - "5000"
    
