version: "3"
services:
  db:
    
    image: abbasshaik739/project1:databaseimage
    ports:
      - "3306"
    networks:
      - appnet


  auth_service:
    
    image: abbasshaik739/project1:authimage
    ports:
      - "5001"
    networks:
      - appnet

  book_service:
    
    image: abbasshaik739/project1:bookimage
    ports:
      - "5002"
    networks:
      - appnet



  borrow_service:
    
    image: abbasshaik739/project1:borrowimage
    ports:
      - "5003"
    networks:
      - appnet


  frontend:
    
    image: abbasshaik739/project1:appimage
    ports:
      - "5000"
    networks:
      - appnet


network:
  appnet:
    
    driver: bridge
