---
version: "3"
services:
  db:
    image: databaseimg
    ports:
      - "3306:3306"
    deploy:
      replicas: 1

   auth:
     image: authimg
     ports:
       - "5001:5001"
     deploy:
       replicas: 1

   book:
     image: bookimg
     ports:
       - "5002:5002"
     deploy:
       replicas: 1

   borrow:
     image: borrowimg
     ports:
       - "5003:5003"
     deploy:
       replicas: 1

   frontend:
     image: frontendimg
     ports:
       - "5000:5000"
     deploy:
       replicas: 1
