version: "3"
services:
  db:
    image: databaseimg
    ports:
      - "3306:3306"
    deploy:
      replicas: 3

  auth_service:
    image: authimg
    ports:
      - "5001:5001"
    deploy:
      replicas: 3

  book_service:
    image: bookimg
    ports:
      - "5002:5002"
    deploy:
      replicas: 3

  borrow_service:
    image: borrowimg
    ports:
      - "5003:5003"
    deploy:
      replicas: 3

  frontend:
    image: frontendimg
    ports:
      - "5000:5000"
    deploy:
      replicas: 3
