version: "3"
services:
  db:
    image: abbasshaik739/project:databaseimg
    ports:
      - "3306"
    deploy:
      replicas: 1

  auth_service:
    image: abbasshaik739/project:authimg
    ports:
      - "5001"
    deploy:
      replicas: 1

  book_service:
    image: abbasshaik739/project:bookimg
    ports:
      - "5002"
    deploy:
      replicas: 1

  borrow_service:
    image: abbasshaik739/project:borrowimg
    ports:
      - "5003"
    deploy:
      replicas: 1

  frontend:
    image: abbasshaik739/project:frontendimg
    ports:
      - "5000"
    deploy:
      replicas: 1
